### PR TITLE
Fixed the image link

### PR DESCRIPTION
**Pull request by email2vimalraj**
The image link was broken and fixed now

### CODE REVIEW

**Comment by bobharley** [comment]
It works just fine

**Comment by email2vimalraj** [comment]
@bobharley : No, the link doesn't work when I click from github. 

Refer the below image, and see the hovered link in the left bottom, it points to `fm-md.png` instead of `fb-md.png`.

screen shot 2017-10-08 at 10 26 35 pm

When I click on the image link, I get `Page not found`:

screen shot 2017-10-08 at 10 26 45 pm

**Comment by bobharley** [comment]
I've updated it myself, it works fine now.
If you want to contribute, please follow the [guidelines](https://github.com/bobharley/facebook-md/blob/master/README.md).

**Comment by email2vimalraj** [comment]
Great! If there is a mistake done by the contributor, I would help them to understand the mistake and correct it by themselves. If I missed following guidelines, you would have let me know and I'll happily update the commit with what should I've followed. Thanks for demotivating me in contributing.

**Comment by bobharley** [comment]
Demotivating you? Dude, you just removed like 6 characters from the readme.md

**Comment by email2vimalraj** [comment]
Dude, I fixed the problem that you never observed. Readme is the user
facing and should give appropriate information. 6 or 1000 characters
shouldn't be a deciding factor of the contribution.

**Comment by bobharley** [comment]
Your fork is behind the master branch. It was easier to fix the "readme.md" file myself.
I'm sure you're still motivated to find typos on other people's readme.md files. Don't worry, your PR still counts for the hacktoberfest.

If you want to "actually" contribute, "read and follow" the [guidelines](https://github.com/bobharley/facebook-md/blob/master/README.md) and also read the issues on the [issues](https://github.com/bobharley/facebook-md/blob/master/README.md) page. Thanks!

**Comment by bobharley** [comment]
"never observed" how did you know?

**Pull request closed without merging**
